export const products = [
    "мука пшеничная",
    "кефир",
    "сахар",
    "яйцо",
    "какао",
    "масло",
    "ванилин",
    "вода",
    "сметана",
    "чай",
    "судак",
    "укроп",
    "петрушка",
    "лук",
    "печень",
    "свинина",
    "чеснок",
    "сало",
    "Курица",
    "перец",
    "паприка",
    "соль",
    "соевый соус",
    "свинина",
]
export const menu = [
    {
        img: "https://daily-menu.ru/public/modules/dailymenu/dailymenurecipes/91459/cfdd1c61d2b30fa42e92136e3dc3d324.jpg",
        time: "15",
        cal: "408",
        b: "7.1",
        j: "13",
        u: "69",
        ingredients:"мука пшеничная , кефир 2,5% жирности, сахар-песок, яйцо куриное, какао-порошок, масло подсолнечное, ванилин",
        title:"Шоколадный кекс",
    },
    {
        img: "https://daily-menu.ru/public/modules/dailymenu/dailymenurecipes/5201/a1a266a5a66b53a146105cb157abfcca.jpg",
        time: "1",
        cal: "0",
        b: "0",
        j: "0",
        u: "0",
        ingredients: "вода",
        title:"вода",

    },
    {
        img: "https://daily-menu.ru/public/modules/dailymenu/dailymenurecipes/76316/5ca484b09ea6d55d282f52a938ee406f.jpg",
        time: "30",
        cal: "605",
        b: "14.6",
        j: "15.3",
        u: "107.8",
        ingredients: "Овсяное печенье ",
        title:"мука овсяная, мука пшеничная , сахар-песок, яйцо куриное, масло сливочное 72%, сметана 15,0% жирности, мед натуральный (мёд), пищевая сода",
    },
    {
        img: "https://daily-menu.ru/public/modules/dailymenu/dailymenurecipes/173007/e6d154346e6cbc03dde5b1a047529589.jpg",
        time: "5",
        cal: "376",
        b: "12.8",
        j: "0.6",
        u: "72.4",
        ingredients: "кус-кус",
                title:"кус-кус",

    },
    {
        img: "https://daily-menu.ru/public/modules/dailymenu/dailymenurecipes/104774/dce7ecf65799a682184462450fb39447.jpg",
        time: "30",
        cal: "385",
        b: "6.8",
        j: "10.3",
        u: "67.9",
        ingredients: "мука пшеничная , сахар-рафинад, масло оливковое, разрыхлитель теста, чай черный байховый",
                title:"блины на чае",

    },
    {
        img: "https://daily-menu.ru/public/modules/dailymenu/dailymenurecipes/116065/1f24ea4eb99811f248bd987ebab4449d.jpg",
        time: "5",
        cal: "178",
        b: "39",
        j: "1.6",
        u: "2.4",
        ingredients: "судак, укроп и другие пряные травы, петрушка, петрушка корень",
                title:"Рыба отварная (судак)",

    },
    {
        img: "https://daily-menu.ru/public/modules/dailymenu/dailymenurecipes/122911/475fac3d4da61145034721b036ec9413.jpg",
        time: "10",
        cal: "248",
        b: "39",
        j: "43",
        u: "2.7",
        ingredients: "куриная печень, лук репчатый, масло подсолнечное",
                title:"Куриная печень тушеная",

    },
    {
        img: "https://daily-menu.ru/public/modules/dailymenu/dailymenurecipes/58765/1b03bb87f92d6d7f0665eb93835bbb9b.jpg",
        time: "5",
        cal: "229",
        b: "37.3",
        j: "9",
        u: "0",
        ingredients: "филе лососевых рыб",
                title:"Стейк из лосося ",

    },
    {
        img: "https://daily-menu.ru/public/modules/dailymenu/dailymenurecipes/181086/94b5a1ebe28b599f5addc78df2ef2903.jpg",
        time: "60",
        cal: "826",
        b: "11",
        j: "86.3",
        u: "1",
        ingredients: "свинина грудинка мякоть, соль поваренная пищевая, чеснок",
                title:"Вареная свиная грудинка",

    },
    {
        img: "https://daily-menu.ru/public/modules/dailymenu/dailymenurecipes/191018/86fdaa50999421b2ef2d552dcd6c9177.jpg",
        time: "15",
        cal: "640",
        b: "6.5",
        j: "68.7",
        u: "1.1",
        ingredients: "салосало, курица филе, без кожи, чеснок, соль поваренная пищевая, паприка сушёная, молотая, перец черный молотый",
                title:"Рулет из сала с курицей ",

    },
    {
        img: "https://daily-menu.ru/public/modules/dailymenu/dailymenurecipes/204429/718afdc657a44ab1b9188b6fc5d9426d.jpg",
        time: "20",
        cal: "199",
        b: "18.6",
        j: "14.7",
        u: "7.1",
        ingredients: `
        бедро куриное с кожей, мед натуральный (мёд), соевый соус, чеснок, масло оливковое, соль поваренная пищевая, паприка сушёная, молотая, перец черный молотый
        `,
        title:"Курица в медовом соусе",

    },

]